### ISSUE TITLE
Crash when replacing number with an int with a none cell

### ISSUE THREAD

**Issue by farkon00** [farkon00/elow#1]
```
Traceback (most recent call last):
  File "/mnt/c/data/elow/main.py", line 73, in <module>
    curses.wrapper(main)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/mnt/c/data/elow/main.py", line 70, in main
    render(console, display.render())
  File "/mnt/c/data/elow/display.py", line 121, in render
    return self.table_display.render()
  File "/mnt/c/data/elow/display.py", line 95, in render
    col_sizes = self._get_col_sizes()
  File "/mnt/c/data/elow/display.py", line 34, in _get_col_sizes
    col_sizes[col] = max(len(str(cell)), col_sizes[col])
  File "/mnt/c/data/elow/cell.py", line 108, in __str__
    return self._cell_displayers[self.type](self)
  File "/mnt/c/data/elow/cell.py", line 85, in display_formula_cell
    return self._display_number(val)
  File "/mnt/c/data/elow/cell.py", line 64, in _display_number
    if num.is_integer():
AttributeError: 'int' object has no attribute 'is_integer'
```

I was replacing a number cell, that has 12 in it with a none cell.

**Comment by farkon00** [comment]
Failed to reproduce, if anyone finds a way to reproduce, please comment here.
